
on:
  workflow_dispatch: ~
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/10 * * * *'

name: Send Data Email

jobs:
  build:
    name: Send Data Email
    runs-on: ubuntu-latest
    steps:
      - name: Get current date and timestamp
        id: timestamp
        run: | 
          echo "::set-output name=datestamp::$(date +'%Y-%m-%d')"
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: FOIA Request (${{ steps.timestamp.outputs.datestamp }})
          # Required recipients' addresses:
          to: austinjckson@gmail.com
          #to: publicinfo@uh.edu
          # Required sender full name (address can be skipped):
          from: Austin Jackson
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: |
            Hello my name is Austin Jackson,

            ${{secrets.MAIL_PERSONAL_INFO}}
            
            I am requesting the grade distributions by percent and/or letter grade, for every class and instructor for the Spring 2021 semester at the University of Houston. Please ensure the documents are FERPA compliant. I request that the information is in CSV format, and in digital format. Preferably in the form:

            Course Subject, Course Number, Course Title, Course Section, Term/Semester, Primary Instructor, A+, A, A-, B+, B, B-, C+, C, C-, D+, D, D-, F, W, Average Grade in GPA, S (Satisfactory), NCR (No Credit Reported).

            Please note, I have included the "S" and "NCR" fields as part of the [Spring 2020 Interim Grade Policy](https://web.archive.org/web/20210415040609/https://uh.edu/provost/policies-resources/student/interim-undergraduate-grade-policy/index). If including these fields is extra work or otherwise incompatible with your procedures, please do not include them as part of this request.

            In addition, if putting in that form is extra work, comma separated value format with the requisite information is acceptable.

            Please notify me of any expenses prior to incurring them.

            Thank you,
            Austin Jackson
          # Optional HTML body read from file:
          #html_body: file://README.html
          # Optional carbon copy recipients:
          #cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
          bcc: austinjckson@gmail.com
          # Optional recipient of the email response:
          #reply_to: luke@example.com
          # Optional Message ID this message is replying to:
          #in_reply_to: <random-luke@example.com>
          # Optional unsigned/invalid certificates allowance:
          #ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          #attachments: attachments.zip,git.diff,./dist/static/*.js
          # Optional priority: 'high', 'normal' (default) or 'low'
          #priority: low
